# ~Remember to add and remove 0.0.0.0 in your MongoDB Atlas IP Whitelist
name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: go test -v ./src/main/...