name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Whitelist 0.0.0.0
      run: |
        echo "Whitelisting IP: 0.0.0.0"
        curl -u "${{ secrets.ATLAS_PUBLIC_KEY }}:${{ secrets.ATLAS_PRIVATE_KEY }}" \
          --request POST \
          --url "https://cloud.mongodb.com/api/atlas/v2/groups/${{ secrets.ATLAS_PROJECT_ID }}/accessList" \
          --header "Content-Type: application/json" \
          --data "[{\"ipAddress\": \"0.0.0.0\", \"comment\": \"GitHub Actions runner IP\"}]"

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: go test -v ./src/main/...

    - name: Remove 0.0.0.0 from whitelist
      if: always()
      run: |
        echo "Removing IP: 0.0.0.0 from whitelist"
        curl -u "${{ secrets.ATLAS_PUBLIC_KEY }}:${{ secrets.ATLAS_PRIVATE_KEY }}" \
          --request DELETE \
          --url "https://cloud.mongodb.com/api/atlas/v2/groups/${{ secrets.ATLAS_PROJECT_ID }}/accessList/0.0.0.0"