name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Whitelist GitHub Actions runner IP
      uses: mongodb-developer/mongodb-atlas-ip-whitelist-action@v0.2.0
      with:
        publicKey: ${{ secrets.ATLAS_PUBLIC_KEY }}
        privateKey: ${{ secrets.ATLAS_PRIVATE_KEY }}
        projectId: ${{ secrets.ATLAS_PROJECT_ID }}
        deleteAfterSeconds: 600 # Optional: Automatically remove the IP after 10 minutes

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: go test -v ./src/main/...