name: CI/CD

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: go build -v ./...

    - name: Test
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: go test -v ./...

  create-pull-request:
    needs: build
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        branch: main
        base: development
        title: 'Automated Pull Request from Development to Main'
        body: 'This pull request is automatically created by GitHub Actions.'