name: Go

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: go build -v ./...

    - name: Test
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: go test -v ./...